language: en
html:
  use_issues_button: false
  use_repository_button: true

repository:
  url: https://github.com/UCB-stat-159-f25/proj02-group20
  path_to_book: ""
  branch: main

execute:
  execute_notebooks: "off"
