name: sotu
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - jupyterlab
  - ipykernel
  - ipywidgets
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - numba
  - numexpr
  - spacy
  - gensim
  - umap-learn
  - hdbscan
  - matplotlib
  - seaborn
  - plotly
  - tqdm
  - rich
  - requests
  - pip:
    - bertopic
	- sentence-transformers
	- transformers
	- torch
	- pyldavis